### DISCUSSION TITLE
A3: Better on-boarding experience for newcomers

### DISCUSSION THREAD

**Discussion by myovchev** [apostrophecms/apostrophe#3262] [Ideas]
I've just met a confused person coming from the PHP world, who wasn't able to boot up an Apostrophe app on a local machine following the official [getting started guide](https://v3.docs.apostrophecms.org/guide/setting-up.html)

I think there is a room for improvement here when it comes to meeting the system requirements and especially MongoDB and NodeJS. A typical and easy to setup environment  for Linux (and I believe MacOS as well) would be docker compose and `nvm`. 
Docker has very good installation documentation for every OS so it can be directly linked. When it comes to MongoDB a template `docker-compose.yml` file like this one could be embed in the docs:
```yml
version: "2"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

volumes:
  mongodb-data:
```
with `docker-compose up -d` and `docker-compose down` for respectively start and stop the mongodb instance.
The `nvm` tool has even more simple installation procedure (via remote bash script) for *nix systems (completely in the dark about Windows development environment though, haven't do that 10+ years). The only thing left is the nvm command to download and setup as default (or via ,nvmrc project file) the correct NodeJS version.

Of course, something already discussed I guess would be a ready to go Apostrophe docker image and/or docker compose running both mongodb and the local app and while this is solid option, I think the above would be great for people to understand the semantics. 

I think meeting the environment requirement is a showstopper for newcomers previously using another technologies and it would be great if they don't get stressed by that. I'll be glad to assist with whatever I can regarding the most possible simplified instructions for Linux systems (although I'm sure you have enough experience there :) )
