### ISSUE TITLE
3.0 Aggressive CSS selectors interfering with user defined styles

### ISSUE THREAD

**Issue by myovchev** [apostrophecms/apostrophe#3034]
## To Reproduce
1. Enclose your page (e.g. block `beforeMain` in `views/layout`)  in a container `<main class="my-typography">`
2. Add your CSS
```css
/* My entire page line height */
.my-typography { line-height: 1.75em; }
/* My paragraph specifics */
.my-typography p { padding-bottom: etc }
```
3. Add a paragraph tag to your page (e.g. directly in the block `main`)
4. Inspect the paragraph, it will have `line-height: var(--a-line-base)` because of this selector coming from the apostrophe administration styles:
```css
[class*='apos-'] {
  line-height: var(--a-line-base);
  box-sizing: content-box; }
```
It has higher priority than `.my-typography` selector and it's a hit because the whole page content lives in `.apos-refreshable`.

## Expected behavior
No interference with the user defined styles. Apostrophe shouldn't use wildcard selectors but stick to a specific namespace(s) (e.g. `.apos-admin-bar-wrapper, .apos-modals`) for global admin selectors.

## Details
Tested on chromium engine v90.0.4430.85
